version: '3.7'

services:

  swish-acquisition-test-base:
    image: swish-acquisition-dev:${IMAGE_TAG:-latest}

  swish-acquisition-test:
    extends:
      service: swish-acquisition-test-base
    user: root
    volumes:
      - ./coverage_report:/services/swish/swish-acquisition/coverage_report
    command: make test

  swish-acquisition-lint:
    extends:
      service: swish-acquisition-test-base
    command: make lint

  swish-acquisition-type-hint:
    extends:
      service: swish-acquisition-test-base
    command: make type-hint
