name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  unit-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run unittest cases
        run: |
          make testd
      - name: Test coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.50
        id: coverageComment
        with:
          junitxml-path: coverage_report/pytest.xml
          pytest-xml-coverage-path: coverage_report/cov.xml
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.WORKFLOW_TOKEN }}
          gistID: a85f2da56cf61e1703b531b7ca4df7bc
          filename: badge.svg
          label: Coverage Report
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
