name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run lint check
        run: |
          make lintd

  type-hint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run type hint check
        run: |
          make type-hintd

  unit-test:
    runs-on: ubuntu-latest
    needs: [lint, type-hint]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run unittest cases
        run: |
          make testd
      - name: Test coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.50
        id: coverageComment
        with:
          junitxml-path: coverage_report/pytest.xml
          pytest-xml-coverage-path: coverage_report/cov.xml
      - name: Store coverage meta result
        run:
          echo "${{ steps.coverageComment.outputs.coverage }},${{ steps.coverageComment.outputs.color }}" > result.txt
      - name: Get pull request number
        uses: actions/github-script@v6
        id: getPRNumber
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          result-encoding: string
      - name: Upload coverage meta result
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ steps.getPRNumber.outputs.result }}
          path: result.txt
